### ISSUE TITLE
Bash returns error

### ISSUE THREAD

**Issue by inductor** [mkimuram/k8sviz#5]
bash returns error and cannot generate .png from .out file

```bash
$ ./k8sviz.sh -n default -t png -o default.png
./k8sviz.sh: line 15: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
./k8sviz.sh: line 16: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]

$ ls k8sviz.out
k8sviz.out
```

My bash environment is as follows.

```bash
$ bash --version
GNU bash, バージョン 5.0.16(1)-release (x86_64-apple-darwin18.7.0)
Copyright (C) 2019 Free Software Foundation, Inc.
ライセンス GPLv3+: GNU GPL バージョン 3 またはそれ以降 <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by mkimuram** [comment]
@inductor   

Thank you for your bug report.

Could you replace  `#! /bin/bash` with `#! /usr/bin/env bash` in the script and try it again?

It seems that bash supports associative arrays in bash version 4 or later, and default bash version for osx is version 3. In the script bash is specified as /bin/bash, so the default bash is called, instead of bash version 5 which I guess that you installed.

**Comment by mkimuram** [comment]
As described in #6 , this won't happen in the current version.
